### ISSUE TITLE
Failure at automatic mask creation on sample image

### ISSUE THREAD

**Issue by vigji** [anki-xyz/pipra#1]
I opened (by mistake, not sure how this was supposed to happen wanted to report this as well) the demo segmentation stack (screenshot below) and took the chance to try the automatic grab cut mode. It seems to fail with the following error:

```
Traceback (most recent call last):
  File "/Users/luigipetrucco/anaconda3/envs/pipra/lib/python3.8/site-packages/pipra/pipra.py", line 438, in mouseReleaseEvent
    mask = GrabCut(im, 
  File "/Users/luigipetrucco/anaconda3/envs/pipra/lib/python3.8/site-packages/pipra/grabcut.py", line 24, in GrabCut
    mask, _, _ = cv2.grabCut(im.astype(np.uint8).copy(), # Original image
cv2.error: OpenCV(4.5.2) /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-iwig8vc6/opencv/modules/imgproc/src/grabcut.cpp:557: error: (-5:Bad argument) image must have CV_8UC3 type in function 'grabCut'

```
Relevant part of the conda list:

```
opencv-python             4.5.2.54                 pypi_0    pypi
openssl                   1.1.1k               h9ed2024_0  
pillow                    8.3.0                    pypi_0    pypi
pip                       21.1.3           py38hecd8cb5_0  
pipra                     0.3.3                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyqt5                     5.15.4                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyqtgraph                 0.12.1                   pypi_0    pypi
python                    3.8.0                h359304d_2  
```

Screenshot:

<img width="1435" alt="Screenshot 2021-07-01 at 10 43 56" src="https://user-images.githubusercontent.com/10400212/124095299-d119b700-da59-11eb-81c0-d68073d2d74f.png">

**Comment by anki-xyz** [comment]
GrabCut needs apparently always RGB images. Now images are automatically converted if they are Grayscale. Issue fixed and closed.
